import numpy as numpy
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
Le = numpy.linspace(1.25,5.5,100)
Lm = 16*Le**(-0.4)
plt.plot(Le,Lm,label='Q=4',color='blue')
plt.plot(3.25,10,marker='o',color='blue')
Lm = 25*Le**(-0.4)
plt.plot(Le,Lm,label='Q=5',color='orange')
plt.plot(4.25,14,marker='o',color='orange')
plt.xlabel('$L_{e}$',fontsize=14)
plt.ylabel('$L_{m}$',rotation=90,fontsize=14)
plt.title('$Q = L^{0.2}K^{0.5}$')
plt.box(False)
plt.xticks(numpy.arange(1,6,0.25))
plt.yticks(numpy.arange(8,24,0.5))
plt.grid(True)
plt.legend()
plt.show()
