import graphviz
rh = graphviz.Digraph(node_attr={'shape':'record'},edge_attr={'fontsize':'10'},format='png')
rh.node('n0',r'Nature',color='black',style='filled',fillcolor='lightgreen',shape='ellipse')
rh.node('n1',r'Employer',color='black',style='filled',fillcolor='lightblue')
rh.node('n2',r'Employer',color='black',style='filled',fillcolor='lightpink')
rh.edge('n0','n1',label='High\n(0.6)')
rh.edge('n0','n2',label='Low\n(0.4)')
rh.node('n3',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
rh.node('n4',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
rh.edge('n1','n3',label='High')
rh.edge('n1','n4',label='Low')
rh.node('n5',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
rh.node('n6',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
rh.edge('n2','n5',label='High')
rh.edge('n2','n6',label='Low')
rh.node('n7',r'600\n-250',color='white',style='filled',fillcolor='white')
rh.node('n8',r'0\n0',color='white',style='filled',fillcolor='white')
rh.edge('n3','n7',label='Yes')
rh.edge('n3','n8',label='No')
rh
