import graphviz
tree = graphviz.Digraph(node_attr={'shape':'record'},edge_attr={'fontsize':'10'},format='png')
tree.node('n0',r'Nature',color='black',style='filled',fillcolor='lightgreen',shape='ellipse')
tree.node('n1',r'Employer',color='black',style='filled',fillcolor='lightblue')
tree.node('n2',r'Employer',color='black',style='filled',fillcolor='lightpink')
tree.edge('n0','n1',label='LP=€1,200\n(p=0.6)')
tree.edge('n0','n2',label='LP=€800\n(1-p=0.4)')
tree.node('n3',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
tree.node('n4',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
tree.edge('n1','n3',label='w=€1,000')
tree.edge('n1','n4',label='w=€500')
tree.node('n5',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
tree.node('n6',r'Job candidate',color='black',style='filled',fillcolor='lightblue')
tree.edge('n2','n5',label='w=€1,000')
tree.edge('n2','n6',label='w=€500')
tree.node('n7',r'',color='white',style='filled',fillcolor='white')
tree.node('n8',r'0\n0',color='white',style='filled',fillcolor='white')
tree.edge('n3','n7',label='Accept')
tree.edge('n3','n8',label='Decline')
tree.node('n9',r'',color='white',style='filled',fillcolor='white')
tree.node('n10',r'0\n0',color='white',style='filled',fillcolor='white')
tree.edge('n4','n9',label='Accept')
tree.edge('n4','n10',label='Decline')
tree.node('n11',r'',color='white',style='filled',fillcolor='white')
tree.node('n12',r'0\n0',color='white',style='filled',fillcolor='white')
tree.edge('n5','n11',label='Accept')
tree.edge('n5','n12',label='Decline')
tree.node('n13',r'',color='white',style='filled',fillcolor='white')
tree.node('n14',r'0\n0',color='white',style='filled',fillcolor='white')
tree.edge('n6','n13',label='Accept')
tree.edge('n6','n14',label='Decline')
tree.node('n15',r'Reservation wage=0.5LP',color='white',style='filled',fillcolor='white')
